-- AlterTable
ALTER TABLE "Payment" ADD COLUMN     "baseAmount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "bonus" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "discountPct" INTEGER NOT NULL DEFAULT 0;
